version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - rede-angular-fastapi

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "4200:80"
    networks:
      - rede-angular-fastapi

networks:
  rede-angular-fastapi:
